### ISSUE TITLE
state-select initial selection ignoring ngModel

### ISSUE THREAD

**Issue by ben-liang** [nerfe/angularjs-country-state-select#1]
The `state-select` directive works fine for me when `ng-model` is initially clean (null), but when I load a form with an existing value saved for `ng-model`, that value is ignored and the initial selection for the `select` element is set to the default.  My code is below.
### Controller

``` js
$scope.organization = {
    city: "Tuscon"
    state: "Arizona"
    country: "USA"
    zip: "93901"
}
```
### Template

``` html
<div class="row mr0 ml0">
    <div class="col-md-4">
        <div class="form-group pr">
            <label for="city">City *</label>
            <input type="text" id="city" name="city" required="required" class="form-control"  data-ng-model="organization.city" placeholder="Funkytown">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group pr">
            <label for="state">State/Province/Region *</label>
            <div id="state" required="required" class="form-control" country="{{ organization.country }}" data-ng-model="organization.state" state-select></div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="zip">Zip/Postal Code *</label>
            <input type="text" id="zip" name="zip" required="required" class="form-control" data-ng-model="organization.zip" placeholder="86753">
        </div>
    </div>
</div>
<div class="row mr0 ml0">
    <div class="col-sm-12">
        <div class="form-group">
            <label for="country">Country *</label>
            <div id="country" required="required" class="form-control" data-ng-model="organization.country" country-select></div>
        </div>
    </div>
</div>
<div class="text-center form-group mt">
    <button type="submit" class="btn btn-large btn-primary">Save Organization</button>
</div>
```
### Result

<img width="761" alt="screen shot 2016-06-06 at 3 26 56 pm" src="https://cloud.githubusercontent.com/assets/9387648/15834784/25d7bde0-2bfb-11e6-8432-292b3a1eadda.png">

**Comment by nerfe** [comment]
Hi Ben,

I will be updating this repo soon, i have been using an updated one, i was just busy in my work, but you can add this in your controller

`        $scope.vm = {
            selectedFamilyMember: "Belize" // or the country you stored in your database
        }`

Thanks

**Comment by nerfe** [comment]
Hi Ben,

Sorry, i will update this repo soon, with the new version, for now you can add this in your controller

`        $scope.vm = {
            selectedFamilyMember: "COUNTRY",
            state: "STATE"
        }`

Thanks

**Comment by wassapaks** [comment]
Hi ben

I will update this repo soon, but you need to add a comma separator to your object,

`$scope.organization = {
    city: "Tuscon",
    state: "Arizona",
    country: "USA",
    zip: "93901"
}`

Thanks

**Comment by ben-liang** [comment]
Sorry, just a typo.  The object is for demonstrative purposes, that's not the actual source I'm using.

**Comment by wassapaks** [comment]
Hello Ben,

I tested your script and its working fine, i just added the comma separator on your object.

**Comment by wassapaks** [comment]
I copied your code please check this,

http://jsbin.com/zimilus/edit?html,js,output
